### ISSUE TITLE
Why use `<link href="data:text/css; ...">` instead of `<style>`?

### ISSUE THREAD

**Issue by jhildenbiddle** [nhn/tui.image-editor#758]
**Summary**

What is the purpose of injecting CSS using a `<link href="data:text/css;charset=UTF-8, ...">` element instead of a `<style>` element?

I'm asking because I recently had a [PR submitted](https://github.com/jhildenbiddle/get-css-data/pull/15) for a library I created called [get-css-data](https://github.com/jhildenbiddle/get-css-data) to handle this use case. The PR author mentioned this project as an example of where loading CSS using this method was done, so I figured I'd ask and maybe learn something new. 🤓 

**Screenshots**

Here is the `<link>` markup I found that uses this technique in the [image editor demo](https://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi):

```html
<link rel="stylesheet" type="text/css" href="data:text/css;charset=UTF-8,%0A%20%20%20%20.tie-icon-add-button.icon-bubble%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-bubble%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-heart%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-heart%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-location%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-location%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-polygon%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-polygon%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-star%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-star%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-star-2%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-star-2%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-arrow-3%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-arrow-3%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-arrow-2%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-arrow-2%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-arrow%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-arrow%22%5D%20label%2C%0A%20%20%20%20.tie-icon-add-button.icon-bubble%20.tui-image-editor-button%5Bdata-icontype%3D%22icon-bubble%22%5D%20label%2C%0A%20%20%20%20.tie-draw-line-select-button.line%20.tui-image-editor-button.line%20label%2C%0A%20%20%20%20.tie-draw-line-select-button.free%20.tui-image-editor-button.free%20label%2C%0A%20%20%20%20.tie-flip-button.flipX%20.tui-image-editor-button.flipX%20label%2C%0A%20%20%20%20.tie-flip-button.flipY%20.tui-image-editor-button.flipY%20label%2C%0A%20%20%20%20.tie-flip-button.resetFlip%20.tui-image-editor-button.resetFlip%20label%2C%0A%20%20%20%20.tie-crop-button%20.tui-image-editor-button.apply.active%20label%2C%0A%20%20%20%20.tie-crop-preset-button%20.tui-image-editor-button.preset.active%20label%2C%0A%20%20%20%20.tie-resize-button%20.tui-image-editor-button.apply.active%20label%2C%0A%20%20%20%20.tie-resize-preset-button%20.tui-image-editor-button.preset.active%20label%2C%0A%20%20%20%20.tie-shape-button.rect%20.tui-image-editor-button.rect%20label%2C%0A%20%20%20%20.tie-shape-button.circle%20.tui-image-editor-button.circle%20label%2C%0A%20%20%20%20.tie-shape-button.triangle%20.tui-image-editor-button.triangle%20label%2C%0A%20%20%20%20.tie-text-effect-button%20.tui-image-editor-button.active%20label%2C%0A%20%20%20%20.tie-text-align-button.tie-text-align-left%20.tui-image-editor-button.left%20label%2C%0A%20%20%20%20.tie-text-align-button.tie-text-align-center%20.tui-image-editor-button.center%20label%2C%0A%20%20%20%20.tie-text-align-button.tie-text-align-right%20.tui-image-editor-button.right%20label%2C%0A%20%20%20%20.tie-mask-apply.apply.active%20.tui-image-editor-button.apply%20label%2C%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-submenu%20.tui-image-editor-button%3Ahover%20%3E%20label%2C%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-checkbox%20label%20%3E%20span%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23fff%3Bfont-weight%3A%20lighter%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-submenu%20.tui-image-editor-button%20%3E%20label%2C%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-range-wrap.tui-image-editor-newline.short%20label%2C%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-range-wrap.tui-image-editor-newline.short%20label%20%3E%20span%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%238a8a8a%3Bfont-weight%3A%20lighter%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-range-wrap%20label%20%3E%20span%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23fff%3Bfont-weight%3A%20lighter%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-partition%20%3E%20div%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%233c3c3c%3Bborder-left%3A%201px%20solid%20%233c3c3c%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container.left%20.tui-image-editor-submenu%20.tui-image-editor-partition%20%3E%20div%2C%0A%20%20%20%20.tui-image-editor-container.right%20.tui-image-editor-submenu%20.tui-image-editor-partition%20%3E%20div%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%233c3c3c%3Bborder-bottom%3A%201px%20solid%20%233c3c3c%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-checkbox%20label%20%3E%20span%3Abefore%20%7B%0A%20%20%20%20%20%20%20%20border%3A%200px%3Bbackground-color%3A%20%23fff%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-checkbox%20label%20%3E%20input%3Achecked%20%2B%20span%3Abefore%20%7B%0A%20%20%20%20%20%20%20%20border%3A%200%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-virtual-range-pointer%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23fff%3Bbackground-color%3A%20%23fff%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-virtual-range-bar%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23666%3Bbackground-color%3A%20%23666%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-virtual-range-subbar%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23d1d1d1%3Bbackground-color%3A%20%23d1d1d1%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-disabled%20.tui-image-editor-virtual-range-pointer%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23414141%3Bbackground-color%3A%20%23414141%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-disabled%20.tui-image-editor-virtual-range-subbar%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23414141%3Bbackground-color%3A%20%23414141%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-disabled%20.tui-image-editor-virtual-range-bar%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23282828%3Bbackground-color%3A%20%23282828%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-range-value%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23fff%3Bfont-weight%3A%20lighter%3Bfont-size%3A%2011px%3Bborder%3A%201px%20solid%20%23353535%3Bbackground-color%3A%20%23151515%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-submenu%20.tui-image-editor-button%20.color-picker-value%20%2B%20label%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20%23fff%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-submenu%20.tui-image-editor-button%20.color-picker-value%20%7B%0A%20%20%20%20%20%20%20%20border%3A%201px%20solid%20%231e1e1e%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.svg_ic-menu%20%7B%0A%20%20%20%20%20%20%20%20width%3A%2024px%3Bheight%3A%2024px%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.svg_ic-submenu%20%7B%0A%20%20%20%20%20%20%20%20width%3A%2032px%3Bheight%3A%2032px%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-controls-logo%20%3E%20img%2C%0A%20%20%20%20.tui-image-editor-container%20.tui-image-editor-header-logo%20%3E%20img%20%7B%0A%20%20%20%20%20%20%20%20width%3A%20251px%3Bheight%3A%2021px%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-menu%20use.normal.use-default%2C%0A%20%20%20%20.tui-image-editor-help-menu%20use.normal.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%238a8a8a%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%238a8a8a%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-menu%20use.active.use-default%2C%0A%20%20%20%20.tui-image-editor-help-menu%20use.active.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%23555555%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%23555555%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-menu%20use.hover.use-default%2C%0A%20%20%20%20.tui-image-editor-help-menu%20use.hover.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%23e9e9e9%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%23e9e9e9%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-menu%20use.disabled.use-default%2C%0A%20%20%20%20.tui-image-editor-help-menu%20use.disabled.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%23434343%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%23434343%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-submenu%20use.normal.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%238a8a8a%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%238a8a8a%3B%0A%20%20%20%20%7D%0A%20%20%20%20.tui-image-editor-submenu%20use.active.use-default%20%7B%0A%20%20%20%20%20%20%20%20fill-rule%3A%20evenodd%3B%0A%20%20%20%20%20%20%20%20fill%3A%20%23e9e9e9%3B%0A%20%20%20%20%20%20%20%20stroke%3A%20%23e9e9e9%3B%0A%20%20%20%20%7D%0A">
```

**Version**

v3.15.2

Thanks!

**Comment by lja1018** [comment]
@jhildenbiddle 
The reason `<link>` was used instead of `<style>` is because the browser cannot handle the CSS when `@import` is used, resulting in longer loading.
I hope that was a good answer.
Note: https://www.stevesouders.com/blog/2009/04/09/dont-use-import/

**Comment by jhildenbiddle** [comment]
Thanks for the reply, @lja1018. 

I'm not sure I'm following your explanation though. There is no `@import` statement involved here. The `<link>` element is using a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) to append the following [URL encoded](https://www.urldecoder.org) CSS:

```css
.tie-icon-add-button.icon-bubble .tui-image-editor-button[data-icontype="icon-bubble"] label,
.tie-icon-add-button.icon-heart .tui-image-editor-button[data-icontype="icon-heart"] label,
.tie-icon-add-button.icon-location .tui-image-editor-button[data-icontype="icon-location"] label,
.tie-icon-add-button.icon-polygon .tui-image-editor-button[data-icontype="icon-polygon"] label,
.tie-icon-add-button.icon-star .tui-image-editor-button[data-icontype="icon-star"] label,
.tie-icon-add-button.icon-star-2 .tui-image-editor-button[data-icontype="icon-star-2"] label,
.tie-icon-add-button.icon-arrow-3 .tui-image-editor-button[data-icontype="icon-arrow-3"] label,
.tie-icon-add-button.icon-arrow-2 .tui-image-editor-button[data-icontype="icon-arrow-2"] label,
.tie-icon-add-button.icon-arrow .tui-image-editor-button[data-icontype="icon-arrow"] label,
.tie-icon-add-button.icon-bubble .tui-image-editor-button[data-icontype="icon-bubble"] label,
.tie-draw-line-select-button.line .tui-image-editor-button.line label,
.tie-draw-line-select-button.free .tui-image-editor-button.free label,
.tie-flip-button.flipX .tui-image-editor-button.flipX label,
.tie-flip-button.flipY .tui-image-editor-button.flipY label,
.tie-flip-button.resetFlip .tui-image-editor-button.resetFlip label,
.tie-crop-button .tui-image-editor-button.apply.active label,
.tie-crop-preset-button .tui-image-editor-button.preset.active label,
.tie-resize-button .tui-image-editor-button.apply.active label,
.tie-resize-preset-button .tui-image-editor-button.preset.active label,
.tie-shape-button.rect .tui-image-editor-button.rect label,
.tie-shape-button.circle .tui-image-editor-button.circle label,
.tie-shape-button.triangle .tui-image-editor-button.triangle label,
.tie-text-effect-button .tui-image-editor-button.active label,
.tie-text-align-button.tie-text-align-left .tui-image-editor-button.left label,
.tie-text-align-button.tie-text-align-center .tui-image-editor-button.center label,
.tie-text-align-button.tie-text-align-right .tui-image-editor-button.right label,
.tie-mask-apply.apply.active .tui-image-editor-button.apply label,
.tui-image-editor-container .tui-image-editor-submenu .tui-image-editor-button:hover > label,
.tui-image-editor-container .tui-image-editor-checkbox label > span {
    color: #fff;font-weight: lighter
}
.tui-image-editor-container .tui-image-editor-submenu .tui-image-editor-button > label,
.tui-image-editor-container .tui-image-editor-range-wrap.tui-image-editor-newline.short label,
.tui-image-editor-container .tui-image-editor-range-wrap.tui-image-editor-newline.short label > span {
    color: #8a8a8a;font-weight: lighter
}
.tui-image-editor-container .tui-image-editor-range-wrap label > span {
    color: #fff;font-weight: lighter
}
.tui-image-editor-container .tui-image-editor-partition > div {
    color: #3c3c3c;border-left: 1px solid #3c3c3c
}
.tui-image-editor-container.left .tui-image-editor-submenu .tui-image-editor-partition > div,
.tui-image-editor-container.right .tui-image-editor-submenu .tui-image-editor-partition > div {
    color: #3c3c3c;border-bottom: 1px solid #3c3c3c
}
.tui-image-editor-container .tui-image-editor-checkbox label > span:before {
    border: 0px;background-color: #fff
}
.tui-image-editor-container .tui-image-editor-checkbox label > input:checked + span:before {
    border: 0;
}
.tui-image-editor-container .tui-image-editor-virtual-range-pointer {
    color: #fff;background-color: #fff
}
.tui-image-editor-container .tui-image-editor-virtual-range-bar {
    color: #666;background-color: #666
}
.tui-image-editor-container .tui-image-editor-virtual-range-subbar {
    color: #d1d1d1;background-color: #d1d1d1
}
.tui-image-editor-container .tui-image-editor-disabled .tui-image-editor-virtual-range-pointer {
    color: #414141;background-color: #414141
}
.tui-image-editor-container .tui-image-editor-disabled .tui-image-editor-virtual-range-subbar {
    color: #414141;background-color: #414141
}
.tui-image-editor-container .tui-image-editor-disabled .tui-image-editor-virtual-range-bar {
    color: #282828;background-color: #282828
}
.tui-image-editor-container .tui-image-editor-range-value {
    color: #fff;font-weight: lighter;font-size: 11px;border: 1px solid #353535;background-color: #151515
}
.tui-image-editor-container .tui-image-editor-submenu .tui-image-editor-button .color-picker-value + label {
    color: #fff
}
.tui-image-editor-container .tui-image-editor-submenu .tui-image-editor-button .color-picker-value {
    border: 1px solid #1e1e1e
}
.tui-image-editor-container .svg_ic-menu {
    width: 24px;height: 24px
}
.tui-image-editor-container .svg_ic-submenu {
    width: 32px;height: 32px
}
.tui-image-editor-container .tui-image-editor-controls-logo > img,
.tui-image-editor-container .tui-image-editor-header-logo > img {
    width: 251px;height: 21px
}
.tui-image-editor-menu use.normal.use-default,
.tui-image-editor-help-menu use.normal.use-default {
    fill-rule: evenodd;
    fill: #8a8a8a;
    stroke: #8a8a8a;
}
.tui-image-editor-menu use.active.use-default,
.tui-image-editor-help-menu use.active.use-default {
    fill-rule: evenodd;
    fill: #555555;
    stroke: #555555;
}
.tui-image-editor-menu use.hover.use-default,
.tui-image-editor-help-menu use.hover.use-default {
    fill-rule: evenodd;
    fill: #e9e9e9;
    stroke: #e9e9e9;
}
.tui-image-editor-menu use.disabled.use-default,
.tui-image-editor-help-menu use.disabled.use-default {
    fill-rule: evenodd;
    fill: #434343;
    stroke: #434343;
}
.tui-image-editor-submenu use.normal.use-default {
    fill-rule: evenodd;
    fill: #8a8a8a;
    stroke: #8a8a8a;
}
.tui-image-editor-submenu use.active.use-default {
    fill-rule: evenodd;
    fill: #e9e9e9;
    stroke: #e9e9e9;
}
```

To simplify the conversation, let's assume that we wanted to append the following CSS to the DOM:

```css
p { color: red; }
```

This would typically be done using a `<style>` element:

```html
<style>
  p { color: red; }
</style>
```

What's happening in the Toast UI Image Editor is that this CSS is being URL encoded...

```
p%20%7B%20color%3A%20red%3B%20%7D
```

... and then appended to the DOM using a `<link>` element with a data URL:

```html
<link href="data:text/css;charset=UTF-8,p%20%7B%20color%3A%20red%3B%20%7D">
```

The question is *why* do the extra work of URL encoding the CSS and using a `<link>` element with a data URL when using a `<style>` tag is so much simpler? 

The only discussion I've found on the topic with any kind of explanation is [this post](https://stackoverflow.com/questions/41082896/why-would-you-use-link-tags-with-a-data-css-href-instead-of-using-a-style-tag) on StackOverflow which provides this answer:

> Pure speculation, but maybe to hide from older browsers? For example, the link won't work on its own in IE.

Based on my testing, this explanation does not appear to be accurate as the following HTML renders red text in IE 9-11:

```html
<p>Foo bar baz</p>

<script>
  var css = '*{color:red;}';
  var link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = 'data:text/css;charset=UTF-8,' + encodeURIComponent(css);
  document.getElementsByTagName('head')[0].appendChild(link);
</script>
```

And so, this remains a mystery to me. :)
