### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by hassanzadeh** [nhn/tui.image-editor#777]
Hey,
I wonder if there is an option to remove the logo ?

**Comment by lja1018** [comment]
@hassanzadeh 
The logo cannot be cleared as an option. However, it is possible by adding the following style.
```css
.tui-image-editor-container .tui-image-editor-header-logo {
  display: none;
}
```
